version: 2.1

jobs:
  tests:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
        name: Install python dependencies
        command: |
          virtualenv ./.venv
          . .venv/bin/activate
          pip install -r requirements.txt
      - run:
        name: Run tests
        command: echo 'This is a test'
          
workflows:
  build_test:
    jobs:
      - tests

