version: 2.1

parameters:
  project-name:
    type: string
    default: 'python-flask'

orbs:
  python: circleci/python@1.2

workflows:
  build_test:
    jobs:
      - run-tests


jobs:
  run-tests:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
        name: Install python dependencies
        command: |
          virtualenv ./.venv
          . .venv/bin/activate
          pip install --user -r requirements.txt
      - run:
        name: Run tests
        command: |
          pytest -v --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

