version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: virtualenv ./.venv
      - run: . .venv/bin/activate
      - run: pip install -r requirements.txt
      - run: pytest -v --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
      - run:
        name: Download
        command: |
            echo "Atma"
          
          
workflows:
  build_test:
    jobs:
      - build


