version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: virtualenv ./.venv
      - run: . .venv/bin/activate
      - run: pip install -r requirements.txt
      - run: pytest -v --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: echo Atma
      - run:
        name: Download
        command: |
        echo Papas
          
workflows:
  build_test:
    jobs:
      - build
      - test
    


