version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: virtualenv ./.venv
      - run: . .venv/bin/activate
      - run: pip install -r requirements.txt
       
  test:
    steps:
      - run: echo "Donas"
        
          
          
workflows:
  build_test:
    jobs:
      - build
      - test

