version: 2.1

jobs:
  tests:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
        name: Install python dependencies
        command: echo 'Papas' 
          
          
workflows:
  build_test:
    jobs:
      - tests

